#
# Comparison WT_vs_Rspondin
# This code was autogenerated
#
plot_and_save_results <- function(results, name) {
	#
	# This function just plots some diagnostic plots and saves the results
	#
	dd = results[with(results,order(padj)),]
	write.csv(dd,paste(name,"_results.csv",sep=""))
	pdf(paste(name,"-pvalue-hist.pdf",sep=""))
	hist(res$pvalue, breaks=20, col="grey")
	dev.off()
	pdf(paste(name,"-padj-hist.pdf",sep=""))
	hist(res$padj, breaks=20, col="grey")
	dev.off()
	pdf(paste(name,"-MA-plot.pdf",sep=""))
	plotMA(results)
	dev.off()
}

library("DESeq2")
library("RColorBrewer")
library("gplots")
library("genefilter")

data <- read.csv("../../HTSeqCount/HTSeq.geneSymbol.counts.csv",row.names=1, check.names=FALSE,header=T)
data <- data[rowSums(data)>1,]
data <- data[,c("A1","A2","A5","A6","NAIVE","LIPO","EN15d","EN4d","EN_M","EN_F","NAIVE_F")]
coldata <- data.frame(
	treatment=c(
		rep("WT",length(c("A1","A2","A5","A6","NAIVE","LIPO"))),
		rep("Rspondin",length(c("EN15d","EN4d","EN_M","EN_F","NAIVE_F")))
	),
	row.names=colnames(data)
)
countTable <- DESeqDataSetFromMatrix(countData=data,colData=coldata,design=~treatment)
result <- DESeq(countTable)
res <- results(result)
plot_and_save_results(res, "WT_vs_Rspondin")
